definitions:
  controller.paymentRequestBody:
    properties:
      card_number:
        type: integer
      expiration_date:
        type: string
      security_number:
        type: integer
      token:
        type: string
    type: object
  controller.paymentResponseBody:
    properties:
      result:
        type: string
    type: object
  controller.saleRequestBody:
    properties:
      dni:
        type: integer
      name:
        type: string
      seat_id:
        type: integer
      surname:
        type: string
    type: object
  controller.saleResponseBody:
    properties:
      id:
        type: integer
      passenger:
        $ref: '#/definitions/model.Passenger'
      price:
        type: number
      reservation_date:
        type: string
      seat_id:
        type: integer
    type: object
  controller.salesRequestBody:
    properties:
      sales:
        items:
          $ref: '#/definitions/controller.saleRequestBody'
        type: array
    type: object
  controller.salesResponseBody:
    properties:
      sales:
        items:
          $ref: '#/definitions/controller.saleResponseBody'
        type: array
      token:
        type: string
    type: object
  model.Airport:
    properties:
      id:
        type: integer
      name:
        type: string
      place:
        $ref: '#/definitions/model.Place'
      placeID:
        type: integer
      status:
        type: string
    type: object
  model.Flight:
    properties:
      basePrice:
        type: number
      capacity:
        type: integer
      date:
        type: string
      destination:
        $ref: '#/definitions/model.Airport'
      destinationID:
        type: integer
      id:
        type: integer
      origin:
        $ref: '#/definitions/model.Airport'
      originID:
        type: integer
    type: object
  model.Passenger:
    properties:
      dni:
        type: integer
      id:
        type: integer
      name:
        type: string
      surName:
        type: string
    type: object
  model.Place:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  model.Sale:
    properties:
      id:
        type: integer
      passenger:
        $ref: '#/definitions/model.Passenger'
      passengerID:
        type: integer
      price:
        type: number
      reservationDate:
        type: string
      saleDate:
        $ref: '#/definitions/sql.NullTime'
      seat:
        $ref: '#/definitions/model.Seat'
      seatID:
        type: integer
      token:
        type: string
    type: object
  model.Seat:
    properties:
      flight:
        $ref: '#/definitions/model.Flight'
      flightID:
        type: integer
      id:
        type: integer
      seatLocation:
        type: string
      status:
        type: string
      type:
        $ref: '#/definitions/model.SeatType'
      typeID:
        type: integer
    type: object
  model.SeatType:
    properties:
      category:
        type: integer
      id:
        type: integer
      multiplier:
        type: number
    type: object
  sql.NullTime:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
host: localhost:8080
info:
  contact: {}
  description: Airport Rest API
  title: Airport Application
  version: "1.0"
paths:
  /flights:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Flight'
            type: array
      summary: Get all flights
      tags:
      - flights
  /payment:
    post:
      consumes:
      - application/json
      parameters:
      - description: request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.paymentRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.paymentResponseBody'
      summary: Creates a payment
      tags:
      - payment
  /sales:
    get:
      parameters:
      - description: Sale token
        in: query
        name: token
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/model.Sale'
              type: array
            type: array
      summary: Get sales by token
      tags:
      - sales
    post:
      consumes:
      - application/json
      parameters:
      - description: request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.salesRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.salesResponseBody'
      summary: Creates a sale
      tags:
      - sales
  /seats:
    get:
      parameters:
      - description: origin ID
        in: query
        name: origin
        required: true
        type: integer
      - description: destination ID
        in: query
        name: destination
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Flight'
            type: array
      summary: Get all seats
      tags:
      - seats
swagger: "2.0"
