-- MySQL Script generated by MySQL Workbench
-- lun 30 may 2022 19:29:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema airport
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `airport` ;

-- -----------------------------------------------------
-- Schema airport
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `airport` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `airport` ;

-- -----------------------------------------------------
-- Table `airport`.`places`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airport`.`places` ;

CREATE TABLE IF NOT EXISTS `airport`.`places` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `airport`.`airports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airport`.`airports` ;

CREATE TABLE IF NOT EXISTS `airport`.`airports` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` LONGTEXT NULL DEFAULT NULL,
  `place_id` BIGINT NULL DEFAULT NULL,
  `status` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_airports_place` (`place_id` ASC) VISIBLE,
  CONSTRAINT `fk_airports_place`
    FOREIGN KEY (`place_id`)
    REFERENCES `airport`.`places` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `airport`.`flights`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airport`.`flights` ;

CREATE TABLE IF NOT EXISTS `airport`.`flights` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `capacity` BIGINT NULL DEFAULT NULL,
  `base_price` FLOAT NULL DEFAULT NULL,
  `date` DATETIME(3) NULL DEFAULT NULL,
  `origin_id` BIGINT NULL DEFAULT NULL,
  `destination_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_flights_origin` (`origin_id` ASC) VISIBLE,
  INDEX `fk_flights_destination` (`destination_id` ASC) VISIBLE,
  CONSTRAINT `fk_flights_destination`
    FOREIGN KEY (`destination_id`)
    REFERENCES `airport`.`airports` (`id`),
  CONSTRAINT `fk_flights_origin`
    FOREIGN KEY (`origin_id`)
    REFERENCES `airport`.`airports` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `airport`.`passengers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airport`.`passengers` ;

CREATE TABLE IF NOT EXISTS `airport`.`passengers` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` LONGTEXT NULL DEFAULT NULL,
  `sur_name` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `airport`.`seat_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airport`.`seat_types` ;

CREATE TABLE IF NOT EXISTS `airport`.`seat_types` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `category` BIGINT NULL DEFAULT NULL,
  `multiplier` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `airport`.`seats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airport`.`seats` ;

CREATE TABLE IF NOT EXISTS `airport`.`seats` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `flight_id` BIGINT NULL DEFAULT NULL,
  `seat_location` LONGTEXT NULL DEFAULT NULL,
  `type_id` BIGINT NULL DEFAULT NULL,
  `status` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_seats_flight` (`flight_id` ASC) VISIBLE,
  INDEX `fk_seats_type` (`type_id` ASC) VISIBLE,
  CONSTRAINT `fk_seats_flight`
    FOREIGN KEY (`flight_id`)
    REFERENCES `airport`.`flights` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_seats_type`
    FOREIGN KEY (`type_id`)
    REFERENCES `airport`.`seat_types` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `airport`.`sales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airport`.`sales` ;

CREATE TABLE IF NOT EXISTS `airport`.`sales` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `passenger_id` BIGINT NULL DEFAULT NULL,
  `seat_id` BIGINT NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  `sale_date` DATETIME(3) NULL DEFAULT NULL,
  `reservation_date` DATETIME(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sales_passenger` (`passenger_id` ASC) VISIBLE,
  INDEX `fk_sales_seat` (`seat_id` ASC) VISIBLE,
  CONSTRAINT `fk_sales_passenger`
    FOREIGN KEY (`passenger_id`)
    REFERENCES `airport`.`passengers` (`id`),
  CONSTRAINT `fk_sales_seat`
    FOREIGN KEY (`seat_id`)
    REFERENCES `airport`.`seats` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `airport`.`places`
-- -----------------------------------------------------
START TRANSACTION;
USE `airport`;
INSERT INTO `airport`.`places` (`id`, `name`) VALUES (1, 'CABA');
INSERT INTO `airport`.`places` (`id`, `name`) VALUES (DEFAULT, 'San Miguel');
INSERT INTO `airport`.`places` (`id`, `name`) VALUES (DEFAULT, 'Bariloche');

COMMIT;


-- -----------------------------------------------------
-- Data for table `airport`.`airports`
-- -----------------------------------------------------
START TRANSACTION;
USE `airport`;
INSERT INTO `airport`.`airports` (`id`, `name`, `place_id`, `status`) VALUES (1, 'Jorge Newbery', 1, '');
INSERT INTO `airport`.`airports` (`id`, `name`, `place_id`, `status`) VALUES (DEFAULT, 'Teniente Luis Candelaria', 3, NULL);
INSERT INTO `airport`.`airports` (`id`, `name`, `place_id`, `status`) VALUES (DEFAULT, 'Aeropuerto de Campo de Mayo', 2, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `airport`.`flights`
-- -----------------------------------------------------
START TRANSACTION;
USE `airport`;
INSERT INTO `airport`.`flights` (`id`, `capacity`, `base_price`, `date`, `origin_id`, `destination_id`) VALUES (1, 50, 3000, '2022-12-18 13:17:17', 1, 2);
INSERT INTO `airport`.`flights` (`id`, `capacity`, `base_price`, `date`, `origin_id`, `destination_id`) VALUES (DEFAULT, 50, 4000, '2022-06-18 13:17:17', 1, 3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `airport`.`seat_types`
-- -----------------------------------------------------
START TRANSACTION;
USE `airport`;
INSERT INTO `airport`.`seat_types` (`id`, `category`, `multiplier`) VALUES (1, 1, 1);
INSERT INTO `airport`.`seat_types` (`id`, `category`, `multiplier`) VALUES (2, 2, 1.5);

COMMIT;


-- -----------------------------------------------------
-- Data for table `airport`.`seats`
-- -----------------------------------------------------
START TRANSACTION;
USE `airport`;
INSERT INTO `airport`.`seats` (`id`, `flight_id`, `seat_location`, `type_id`, `status`) VALUES (1, 1, 'A1', 1, 'EMPTY');
INSERT INTO `airport`.`seats` (`id`, `flight_id`, `seat_location`, `type_id`, `status`) VALUES (DEFAULT, 1, 'A2', 1, 'EMPTY');
INSERT INTO `airport`.`seats` (`id`, `flight_id`, `seat_location`, `type_id`, `status`) VALUES (DEFAULT, 1, 'A3', 1, 'EMPTY');
INSERT INTO `airport`.`seats` (`id`, `flight_id`, `seat_location`, `type_id`, `status`) VALUES (DEFAULT, 1, 'A4', 1, 'EMPTY');
INSERT INTO `airport`.`seats` (`id`, `flight_id`, `seat_location`, `type_id`, `status`) VALUES (DEFAULT, 1, 'A5', 2, 'EMPTY');
INSERT INTO `airport`.`seats` (`id`, `flight_id`, `seat_location`, `type_id`, `status`) VALUES (DEFAULT, 1, 'A6', 2, 'EMPTY');
INSERT INTO `airport`.`seats` (`id`, `flight_id`, `seat_location`, `type_id`, `status`) VALUES (DEFAULT, 1, 'A7', 2, 'EMPTY');

COMMIT;

