DROP TABLE IF EXISTS airports;
DROP TABLE IF EXISTS flights;
DROP TABLE IF EXISTS passengers;
DROP TABLE IF EXISTS places;
DROP TABLE IF EXISTS sales;
DROP TABLE IF EXISTS seats;
DROP TABLE IF EXISTS seat_types;

