-- MySQL Script generated by MySQL Workbench
-- vie 27 may 2022 19:42:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Data for table `airport`.`places`
-- -----------------------------------------------------
START TRANSACTION;
USE `airport`;
INSERT INTO `airport`.`places` (`id`, `name`) VALUES (1, 'CABA');
INSERT INTO `airport`.`places` (`id`, `name`) VALUES (DEFAULT, 'San Miguel');
INSERT INTO `airport`.`places` (`id`, `name`) VALUES (DEFAULT, 'Bariloche');

COMMIT;


-- -----------------------------------------------------
-- Data for table `airport`.`airports`
-- -----------------------------------------------------
START TRANSACTION;
USE `airport`;
INSERT INTO `airport`.`airports` (`id`, `name`, `place_id`, `status`) VALUES (1, 'Jorge Newbery', 1, 'OPEN');
INSERT INTO `airport`.`airports` (`id`, `name`, `place_id`, `status`) VALUES (DEFAULT, 'Teniente Luis Candelaria', 3, 'OPEN');
INSERT INTO `airport`.`airports` (`id`, `name`, `place_id`, `status`) VALUES (DEFAULT, 'Aeropuerto de Campo de Mayo', 2, 'OPEN');

COMMIT;


-- -----------------------------------------------------
-- Data for table `airport`.`flights`
-- -----------------------------------------------------
START TRANSACTION;
USE `airport`;
INSERT INTO `airport`.`flights` (`id`, `capacity`, `base_price`, `date`, `origin_id`, `destination_id`) VALUES (1, 50, 3000, '2022-12-18 13:17:17', 1, 2);
INSERT INTO `airport`.`flights` (`id`, `capacity`, `base_price`, `date`, `origin_id`, `destination_id`) VALUES (DEFAULT, 50, 4000, '2022-06-18 13:17:17', 1, 3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `airport`.`seats`
-- -----------------------------------------------------
START TRANSACTION;
USE `airport`;
INSERT INTO `airport`.`seats` (`id`, `flight_id`, `seat_location`, `type_id`, `status`) VALUES (1, 1, 'A1', 1, 'EMPTY');
INSERT INTO `airport`.`seats` (`id`, `flight_id`, `seat_location`, `type_id`, `status`) VALUES (DEFAULT, 1, 'A2', 1, 'EMPTY');
INSERT INTO `airport`.`seats` (`id`, `flight_id`, `seat_location`, `type_id`, `status`) VALUES (DEFAULT, 1, 'A3', 1, 'EMPTY');
INSERT INTO `airport`.`seats` (`id`, `flight_id`, `seat_location`, `type_id`, `status`) VALUES (DEFAULT, 1, 'A4', 1, 'EMPTY');
INSERT INTO `airport`.`seats` (`id`, `flight_id`, `seat_location`, `type_id`, `status`) VALUES (DEFAULT, 1, 'A5', 2, 'EMPTY');
INSERT INTO `airport`.`seats` (`id`, `flight_id`, `seat_location`, `type_id`, `status`) VALUES (DEFAULT, 1, 'A6', 2, 'EMPTY');
INSERT INTO `airport`.`seats` (`id`, `flight_id`, `seat_location`, `type_id`, `status`) VALUES (DEFAULT, 1, 'A7', 2, 'EMPTY');

COMMIT;

